# DEAR STUDENTS, PLEASE DO NOT CHANGE THIS FILE AS IT INFLUENCES THE CI
# PIPELINE ON GITLAB. MESSING WITH THIS CONFIGURATION CAN CAUSE FAILURE
# OF THE AUTOMATIC ASSIGNMENT GRADING WHICH WE IMPLEMENTED FOR YOUR CONVENIENCE.
#
# MALICIOUS TAMPERING WITH THIS CONFIGURATION RESUlTING IN EXCESSIVE RUNNER MINUTE
# CONSUMPTION OR OTHER HARM CAN HAVE CONSEQUENCES.
#
# IF YOU RUN INTO ISSUES, CONTACT YOUR TA.
#
# THANK YOU FOR UNDERSTANDING.

stages:
  - test

runScripts:
  stage: test
  image: registry.inf.ethz.ch/course-pprog21/test_image:v0.1
  script: /bin/bash /runAllUnittestsScript.sh $CI_PROJECT_DIR